language: node_js
node_js:
- '6'
services:
- mongodb
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  bucket: brewerbucket
  region: us-west-2
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: brewerbucket
  key: latest.zip
  bundle_type: zip
  application: codebrewers
  deployment_group: master
  region: us-west-2
before_deploy:
- zip -r latest *
- mkdir -p dpl_cd_upload
- mv latest.zip dpl_cd_upload/latest.zip