sudo: required
dist: trusty
language: node_js
node_js:
- '6'
services:
- mongodb
addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
- npm install -g angular-cli
- npm install -g karma
- npm install
- ng build
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  bucket: brewerbucket
  region: us-west-2
  on:
    repo: "https://github.com/hrr18-codebrewers/ventureout"
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: brewerbucket
  key: latest.zip
  bundle_type: zip
  application: codebrewers
  deployment_group: master
  region: us-west-2
  on:
    repo: "https://github.com/hrr18-codebrewers/ventureout"
before_deploy:
- zip -r latest *
- mkdir -p dpl_cd_upload
- mv latest.zip dpl_cd_upload/latest.zip



